In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [23]:
df = pd.DataFrame(
    {'name':['mohan','sara','sakib','tao','virat','alistair','amroy','rahul','aaron'],
     'height':[1.2,2.3,4.9,5.1,5.2,3.2,2.9,14.5,5.8]}
)

In [24]:
df

       name  height
0     mohan     1.2
1      sara     2.3
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5  alistair     3.2
6     amroy     2.9
7     rahul    14.5
8     aaron     5.8

In [25]:
q1= df['height'].quantile(0.25)
q1

2.9

In [26]:
q3 = df['height'].quantile(0.75)
q3

5.2

In [27]:
iqr = q3-q1
iqr

2.3000000000000003

In [28]:
lower_limit = q1-1.5*iqr
lower_limit

-0.5500000000000003

In [29]:
upper_limit = q3 + 1.5 * iqr
upper_limit

8.65

In [30]:
outlier_data = df[(df['height'] < lower_limit) | (df['height'] >= upper_limit)]
outlier_data

    name  height
7  rahul    14.5

In [31]:
non_outlier_data = df[(df['height']> lower_limit) & (df['height']< upper_limit)]
non_outlier_data

       name  height
0     mohan     1.2
1      sara     2.3
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5  alistair     3.2
6     amroy     2.9
8     aaron     5.8

In [32]:
#2nd method standard deviation

In [33]:
df['height'].mean()

5.01111111111111

In [34]:
df['height'].std()

3.8782871362382534

In [ ]:
upper_limit_std = df['height'].mean()+3*df['height'].std()
upper_limit_std

16.64597251982587

In [39]:
lower_limit_std = df['height'].mean() -3 * df['height'].std()
lower_limit_std

-6.62375029760365

In [40]:
outlier_data_std = df[(df['height'] < lower_limit_std) | (df['height'] >= upper_limit_std)]
outlier_data_std

Empty DataFrame
Columns: [name, height]
Index: []

In [42]:
#method Z score z= x-u(mean)/std_dev

In [43]:
df['height'].mean()

5.01111111111111

In [44]:
df['height'].std()

3.8782871362382534

In [45]:
df['zscore_height']= (df['height']-df['height'].mean())/df['height'].std()
df['zscore_height']

0   -0.982679
1   -0.699049
2   -0.028650
3    0.022920
4    0.048704
5   -0.466987
6   -0.544341
7    2.446670
8    0.203412
Name: zscore_height, dtype: float64

In [ ]:
df['zscore_height'].max()  #upper limit

2.4466700261117444

In [ ]:
df['zscore_height'].min() #lower limit

-0.982678944913733

In [49]:
outlier_data_zscore = df['height'] > df['zscore_height'].max()
outlier_data_zscore

0    False
1    False
2     True
3     True
4     True
5     True
6     True
7     True
8     True
Name: height, dtype: bool

In [50]:
df[df['zscore_height']>2.44]

    name  height  zscore_height
7  rahul    14.5        2.44667

In [51]:
df[df['zscore_height']<-0.98]

    name  height  zscore_height
0  mohan     1.2      -0.982679

In [53]:
df[(df['zscore_height']>2.44) | (df['zscore_height']<-0.98)]

    name  height  zscore_height
0  mohan     1.2      -0.982679
7  rahul    14.5       2.446670