In [2]:
import pandas as pd

In [4]:
obj =pd.Series([1,2,3,4],index=['a','b','c','d'])
obj

a    1
b    2
c    3
d    4
dtype: int64

In [4]:
obj = pd.Series([1,2,3,4])
obj

0    1
1    2
2    3
3    4
dtype: int64

In [101]:
obj =pd.Series([1,2,3,4],index=["a","b","e","d"])
print(obj)

a    1
b    2
e    3
d    4
dtype: int64

In [102]:
obj['a']

1

In [9]:
obj[['a','e']]

a    1
e    3
dtype: int64

In [10]:
ser = pd.Series([1,2,3,4])
print(ser[1])

2

In [11]:
ser[2]=30
print(ser)

0     1
1     2
2    30
3     4
dtype: int64

In [12]:
ser[[1,3]] = 50
print(ser)

0     1
1    50
2    30
3    50
dtype: int64

In [13]:
ser>40

0    False
1     True
2    False
3     True
dtype: bool

In [14]:
ser[ser>40]

1    50
3    50
dtype: int64

In [15]:
data = {"mumbai": 3000,"pune":7000, "nagpur":14500, "chennai":5000}
data

{'mumbai': 3000, 'pune': 7000, 'nagpur': 14500, 'chennai': 5000}

In [16]:
#convert dict to series
data1 = pd.Series(data)
print(data1)

mumbai      3000
pune        7000
nagpur     14500
chennai     5000
dtype: int64

In [17]:
data1['mumbai']

3000

In [18]:
data1[['pune','nagpur']]

pune       7000
nagpur    14500
dtype: int64

In [19]:
info = {"city": ["nashik","pune","jaipur"], "salary":[5000,8000,7000]}
info

{'city': ['nashik', 'pune', 'jaipur'], 'salary': [5000, 8000, 7000]}

In [20]:
print(info)

{'city': ['nashik', 'pune', 'jaipur'], 'salary': [5000, 8000, 7000]}

In [21]:
res = pd.Series(info)
res

city      [nashik, pune, jaipur]
salary        [5000, 8000, 7000]
dtype: object

In [22]:
res['city']

['nashik', 'pune', 'jaipur']

In [23]:
res['city'][1]

'pune'

In [26]:
res['salary'][2]

7000

In [30]:
obj4 = pd.Series(data, index=["mumbai","pune", "nagpur", "chennai","bangalore"])
obj4

mumbai        3000.0
pune          7000.0
nagpur       14500.0
chennai       5000.0
bangalore        NaN
dtype: float64

In [31]:
pd.isnull(obj4)

mumbai       False
pune         False
nagpur       False
chennai      False
bangalore     True
dtype: bool

In [32]:
pd.notnull(obj4)

mumbai        True
pune          True
nagpur        True
chennai       True
bangalore    False
dtype: bool

In [33]:
data1

mumbai      3000
pune        7000
nagpur     14500
chennai     5000
dtype: int64

In [34]:
obj4

mumbai        3000.0
pune          7000.0
nagpur       14500.0
chennai       5000.0
bangalore        NaN
dtype: float64

In [36]:
data1 + obj4

bangalore        NaN
chennai      10000.0
mumbai        6000.0
nagpur       29000.0
pune         14000.0
dtype: float64

In [37]:
source_data = {
    'state':["mumnai","chenneai","pune","delhi","nagpur"],
    'year':[2001,2011,2018,2019,2020],
    'population':[1.5,1.7,3.6,2.4,3.2]
    
}

In [38]:
source_data

{'state': ['mumnai', 'chenneai', 'pune', 'delhi', 'nagpur'],
 'year': [2001, 2011, 2018, 2019, 2020],
 'population': [1.5, 1.7, 3.6, 2.4, 3.2]}

In [39]:
pd.Series(source_data)

state         [mumnai, chenneai, pune, delhi, nagpur]
year                   [2001, 2011, 2018, 2019, 2020]
population                  [1.5, 1.7, 3.6, 2.4, 3.2]
dtype: object

In [41]:
df = pd.DataFrame(source_data)
df

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7
2      pune  2018         3.6
3     delhi  2019         2.4
4    nagpur  2020         3.2

In [42]:
df.head()

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7
2      pune  2018         3.6
3     delhi  2019         2.4
4    nagpur  2020         3.2

In [43]:
df.head(3)

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7
2      pune  2018         3.6

In [44]:
df2 = pd.DataFrame(source_data,columns =['state','year','population','debt'],index=['one','two','three','four','five'])
df2

          state  year  population debt
one      mumnai  2001         1.5  NaN
two    chenneai  2011         1.7  NaN
three      pune  2018         3.6  NaN
four      delhi  2019         2.4  NaN
five     nagpur  2020         3.2  NaN

In [45]:
df2['state']

one        mumnai
two      chenneai
three        pune
four        delhi
five       nagpur
Name: state, dtype: object

In [46]:
df2[['state','year']]

          state  year
one      mumnai  2001
two    chenneai  2011
three      pune  2018
four      delhi  2019
five     nagpur  2020

In [47]:
df2.columns

Index(['state', 'year', 'population', 'debt'], dtype='object')

In [49]:
df2.columns=["STATE","YEAR","POP","DEBT"]
df2

          STATE  YEAR  POP DEBT
one      mumnai  2001  1.5  NaN
two    chenneai  2011  1.7  NaN
three      pune  2018  3.6  NaN
four      delhi  2019  2.4  NaN
five     nagpur  2020  3.2  NaN

In [52]:
df2['DEBT']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: DEBT, dtype: object

In [53]:
df2['DEBT'] = 44
df2

          STATE  YEAR  POP  DEBT
one      mumnai  2001  1.5    44
two    chenneai  2011  1.7    44
three      pune  2018  3.6    44
four      delhi  2019  2.4    44
five     nagpur  2020  3.2    44

In [57]:
import numpy as np
df2['DEBT'] = np.arange(1,6)
df2

          STATE  YEAR  POP  DEBT
one      mumnai  2001  1.5     1
two    chenneai  2011  1.7     2
three      pune  2018  3.6     3
four      delhi  2019  2.4     4
five     nagpur  2020  3.2     5

In [58]:
df2['DEBT'] = [10,20,30,40,50]
df2

          STATE  YEAR  POP  DEBT
one      mumnai  2001  1.5    10
two    chenneai  2011  1.7    20
three      pune  2018  3.6    30
four      delhi  2019  2.4    40
five     nagpur  2020  3.2    50

In [61]:
df2.loc["three"]

STATE    pune
YEAR     2018
POP       3.6
DEBT       30
Name: three, dtype: object

In [62]:
df2.loc[['three','four']]

       STATE  YEAR  POP  DEBT
three   pune  2018  3.6    30
four   delhi  2019  2.4    40

In [64]:
df.loc[[0,1]]

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7

In [65]:
df

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7
2      pune  2018         3.6
3     delhi  2019         2.4
4    nagpur  2020         3.2

In [67]:
df.loc[[0,1]]

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7

In [68]:
df.iloc[[2,3,4]]

    state  year  population
2    pune  2018         3.6
3   delhi  2019         2.4
4  nagpur  2020         3.2

In [69]:
df2.iloc[[2,3,4]]

        STATE  YEAR  POP  DEBT
three    pune  2018  3.6    30
four    delhi  2019  2.4    40
five   nagpur  2020  3.2    50

In [73]:
df2

          STATE  YEAR  POP  DEBT
one      mumnai  2001  1.5    10
two    chenneai  2011  1.7    20
three      pune  2018  3.6    30
four      delhi  2019  2.4    40
five     nagpur  2020  3.2    50

In [75]:
df2.iloc[[2,3,4]]

        STATE  YEAR  POP  DEBT
three    pune  2018  3.6    30
four    delhi  2019  2.4    40
five   nagpur  2020  3.2    50

In [77]:
df2.loc[['two','three','four']]

          STATE  YEAR  POP  DEBT
two    chenneai  2011  1.7    20
three      pune  2018  3.6    30
four      delhi  2019  2.4    40

In [83]:
df2.rename(columns={'YEAR':'years'}, inplace =True)

In [84]:
df2

          STATE  years  POP  DEBT
one      mumnai   2001  1.5    10
two    chenneai   2011  1.7    20
three      pune   2018  3.6    30
four      delhi   2019  2.4    40
five     nagpur   2020  3.2    50

In [85]:
df2.rename(columns={"POP":"population"}, inplace = True)

In [86]:
df2

          STATE  years  population  DEBT
one      mumnai   2001         1.5    10
two    chenneai   2011         1.7    20
three      pune   2018         3.6    30
four      delhi   2019         2.4    40
five     nagpur   2020         3.2    50

In [87]:
df2.rename(columns={"DEBT":"debt",'STATE':"state"},inplace=True)

In [88]:
df2

          state  years  population  debt
one      mumnai   2001         1.5    10
two    chenneai   2011         1.7    20
three      pune   2018         3.6    30
four      delhi   2019         2.4    40
five     nagpur   2020         3.2    50

In [89]:
df3 = df.copy()
df3

      state  year  population
0    mumnai  2001         1.5
1  chenneai  2011         1.7
2      pune  2018         3.6
3     delhi  2019         2.4
4    nagpur  2020         3.2

In [92]:
df3=pd.DataFrame(source_data , columns=['state','year','population','debt'])

In [93]:
df3

      state  year  population debt
0    mumnai  2001         1.5  NaN
1  chenneai  2011         1.7  NaN
2      pune  2018         3.6  NaN
3     delhi  2019         2.4  NaN
4    nagpur  2020         3.2  NaN

In [95]:
df3['debt'] = np.arange(10,15)
df3

      state  year  population  debt
0    mumnai  2001         1.5    10
1  chenneai  2011         1.7    11
2      pune  2018         3.6    12
3     delhi  2019         2.4    13
4    nagpur  2020         3.2    14

In [97]:
df3.at[4,'debt']=400

In [98]:
df3

      state  year  population  debt
0    mumnai  2001         1.5    10
1  chenneai  2011         1.7    11
2      pune  2018         3.6    12
3     delhi  2019         2.4    13
4    nagpur  2020         3.2   400

In [99]:
obj = pd.Series(range(3),index=['a','b','c'])

In [100]:
obj

a    0
b    1
c    2
dtype: int64

In [103]:
df3

      state  year  population  debt
0    mumnai  2001         1.5    10
1  chenneai  2011         1.7    11
2      pune  2018         3.6    12
3     delhi  2019         2.4    13
4    nagpur  2020         3.2   400

In [104]:
df3.iloc[[2,4]]

    state  year  population  debt
2    pune  2018         3.6    12
4  nagpur  2020         3.2   400

In [106]:
df3['western']= df3['state']=='mumnai'

In [107]:
df3

      state  year  population  debt  western
0    mumnai  2001         1.5    10     True
1  chenneai  2011         1.7    11    False
2      pune  2018         3.6    12    False
3     delhi  2019         2.4    13    False
4    nagpur  2020         3.2   400    False

In [108]:
del df3['western']

In [109]:
df3

      state  year  population  debt
0    mumnai  2001         1.5    10
1  chenneai  2011         1.7    11
2      pune  2018         3.6    12
3     delhi  2019         2.4    13
4    nagpur  2020         3.2   400

In [114]:
data = pd.DataFrame(np.arange(16).reshape(4,4),columns=['one','two','three','four'],index=['mumbai','pune','chennai','delhi'])

In [115]:
data

         one  two  three  four
mumbai     0    1      2     3
pune       4    5      6     7
chennai    8    9     10    11
delhi     12   13     14    15

In [119]:
 del data['four']

In [120]:
data

         one  two  three
mumbai     0    1      2
pune       4    5      6
chennai    8    9     10
delhi     12   13     14

In [121]:
data.drop(['chennai'])

        one  two  three
mumbai    0    1      2
pune      4    5      6
delhi    12   13     14

In [124]:
data.iloc[[0,1]]

        one  two  three
mumbai    0    1      2
pune      4    5      6

In [125]:
data.loc[['pune']]

      one  two  three
pune    4    5      6

In [126]:
data

         one  two  three
mumbai     0    1      2
pune       4    5      6
chennai    8    9     10
delhi     12   13     14

In [127]:
data['one']

mumbai      0
pune        4
chennai     8
delhi      12
Name: one, dtype: int32

In [128]:
data[['one','two']]

         one  two
mumbai     0    1
pune       4    5
chennai    8    9
delhi     12   13

In [130]:
data.drop('three',axis=1)

         one  two
mumbai     0    1
pune       4    5
chennai    8    9
delhi     12   13

In [137]:
data.at['delhi','two']=22

In [138]:
data

         one  two  three
mumbai     0    1      2
pune       4    5      6
chennai    8    9     10
delhi     12   22     14

In [139]:
data = {'company':['goog','goog','msft','msft'],
        'sales':[200,120,300,230]}

In [140]:
data

{'company': ['goog', 'goog', 'msft', 'msft'], 'sales': [200, 120, 300, 230]}

In [141]:
df4 = pd.DataFrame(data)

In [142]:
df4

  company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230

In [144]:
grouped_data = df4.groupby("company")
print(grouped_data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002B16ECD1C90>

In [145]:
print(grouped_data.mean())

         sales
company
goog     160.0
msft     265.0

In [146]:
grouped_data.min()

         sales
company
goog       120
msft       230

In [148]:
goog_data = df4[df4['company']=="goog"]
goog_data

  company  sales
0    goog    200
1    goog    120

In [ ]:
df4[df4['company']=="msft"]
df4[df4['company']=='goog']

  company  sales
2    msft    300
3    msft    230

In [150]:
df4.value_counts()

company  sales
goog     120      1
         200      1
msft     230      1
         300      1
dtype: int64

In [151]:
df4

  company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230

In [152]:
df4.rename(columns = {'company':'Company'}, inplace =True)

In [153]:
df4

  Company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230

In [156]:
df4.loc[len(df4)]={'Company':'apple','sales':450}

In [157]:
df4

  Company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230
4     NaN    450
5   apple    450

In [158]:
df4 = df4.drop(4)

In [159]:
df4

  Company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230
5   apple    450

In [160]:
df4[((df4['Company']=="apple") | (df4['Company']=="goog"))]

  Company  sales
0    goog    200
1    goog    120
5   apple    450

In [162]:
df4[df4["Company"]=="goog"]

  Company  sales
0    goog    200
1    goog    120

In [163]:
df4[((df4['Company']=='goog') | (df4['Company']=='msft'))]

  Company  sales
0    goog    200
1    goog    120
2    msft    300
3    msft    230